//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class appuser
    {
        public int idappusers { get; set; }
        public int appid { get; set; }
        public string appSecret { get; set; }
        public string apptoken { get; set; }
        public string securitySoup { get; set; }
    }
}
