//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTPUser
    {
        public int id { get; set; }
        public int userid { get; set; }
        public int appid { get; set; }
        public long otpcounter { get; set; }
        public string secret { get; set; }
        public bool seqvalid { get; set; }
        public System.DateTime otpcreated { get; set; }
    }
}
