//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotioncode
    {
        public int ID { get; set; }
        public string userid { get; set; }
        public string promocode { get; set; }
        public Nullable<bool> redeemed { get; set; }
        public Nullable<bool> ismulticode { get; set; }
        public Nullable<int> multicodequantity { get; set; }
        public Nullable<System.DateTime> validuntil { get; set; }
        public string timezone { get; set; }
        public Nullable<bool> codevalid { get; set; }
        public string GetCodeLink { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public Nullable<System.DateTime> validfrom { get; set; }
        public Nullable<int> multiredeemcount { get; set; }
    }
}
