//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int Type { get; set; }
        public int MaxUsers { get; set; }
        public int MaxDataCount { get; set; }
        public int MaxTesterCount { get; set; }
        public bool OnPremisePossible { get; set; }
        public int DataDaysStore { get; set; }
        public Nullable<int> MaxApps { get; set; }
        public Nullable<int> MaxImagesPerApp { get; set; }
        public Nullable<long> StorageQuota { get; set; }
    }
}
