//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<bool> IsTester { get; set; }
        public string emailaddress { get; set; }
        public string AlternateUserId { get; set; }
    }
}
