//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int iduser { get; set; }
        public int appid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
        public string state { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string website { get; set; }
        public string twitter { get; set; }
        public string facebook { get; set; }
        public string linkedin { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string city { get; set; }
        public bool isactive { get; set; }
        public string ppass { get; set; }
    }
}
