//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userappsEntities : DbContext
    {
        public userappsEntities()
            : base("name=userappsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<managementkey> managementkeys { get; set; }
        public virtual DbSet<app> apps { get; set; }
        public virtual DbSet<appuser> appusers { get; set; }
        public virtual DbSet<systemapp> systemapps { get; set; }
        public virtual DbSet<systemappuser> systemappusers { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<OTPUser> OTPUsers { get; set; }
        public virtual DbSet<promotioncode> promotioncodes { get; set; }
    }
}
